### ISSUE TITLE
Twitter link

### ISSUE THREAD

**Issue by WLubka** [cvuuf/church#25]
Dear Team,  Can we add a Twitter bird icon with a link to our Twitter account to our web site by the FB and YT links?  (  https://twitter.com/uuconejo )?    

Willie

**Comment by brianpletcher** [comment]
Is there a reason we didn't use @cvuuf?

Brian

On Sun, Apr 3, 2016 at 9:59 AM -0700, "WLubka" notifications@github.com wrote:

Dear Team,  Can we add a Twitter bird icon with a link to our Twitter account to our web site by the FB and YT links?  (  https://twitter.com/uuconejo )?

Willie

---

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/CVUUFellowship/church/issues/25

**Comment by GrumpyOldTroll** [comment]
it's up
