### ISSUE TITLE
News and Notes Archive is old

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#55]
https://www.chaliceuu.org/blog/news-notes/

Stops 9/21/18, nothing newer.

**Comment by shaneniebergall** [comment]
@GrumpyOldTroll The content on this page is loaded from a javascript snippet:

//cvuuf.us9.list-manage.com/generate-js/?u=400639c1114daae501c63a104&fid=9689&show=52

that's a mailchimp thing, right? Do you want to look into, or give me access to Mailchimp?

I tried increasing the 'show' parameter on that snippet but it didn't increase the count (https://cvuuf.us9.list-manage.com/generate-js/?u=400639c1114daae501c63a104&fid=9689&show=100)

**Comment by GrumpyOldTroll** [comment]
OK, this is a bit complicated.

The technical problem is that the newsletter emails haven't been put in the news and notes folder, and the archive is associated with a folder in mailchimp:
https://mailchimp.com/help/add-an-email-campaign-archive-to-your-website/

So this will require setting the folder for all the news and notes emails (and going forward, getting Dianna to set it reliably as part of a checklist or something when writing the campaign).

However, the best move might be to get something new set up and start moving off mailchimp (and see whether or not we can or should keep the archive after we figure out what we're doing), because we need to change away from mailchimp anyway, probably within the next year or so, due to their changes last year.  The best overview is probably this:
https://davidgaughran.com/2019/05/16/mailchimp-alternatives-criticism-changes-pricing-plans/

The change that will force us to leave is that unsubscribed accounts now count against the total maximum we can have for free, so we'll have to transition before the natural rate of member growth and turnover puts us over.

But among other changes, it also means I can no longer add new users to the account. The prior list was grandfathered, but the new limit is 1, so removing people doesn't get us there, and the only answer is sharing credentials.  (That's possible, but requires coordination to log in because they require a text message or email for verification during login from a new machine.)

I'm thinking of either moving to this one or just moving to groups instead:
https://www.verticalresponse.com/pricing/non-profit/application

What if we make something like an "accounts@chaliceuu.org" or "account-mailings@chaliceuu.org" address, give you the login for that, and you can use that to try signing up on verticalresponse?

**Comment by shaneniebergall** [comment]
Great, all good here. Will continue to monitor over the next few weeks to ensure future newsletters are tagged appropriately

**Comment by shaneniebergall** [comment]
This is now obsolete since @GrumpyOldTroll cleaned up the news/notes section
