### ISSUE TITLE
Annual Auction/Fundraising updates

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#77]
https://www.chaliceuu.org/giving/annual-auctionfundraising/

"The CVUUF Annual Auction will be Saturday, March 2nd 2019, so please save the date!"
Date is in past UPDATED BUT NEEDS 2020 AUC INFO

"2019 Auction, Saturday March 2nd, 5pm!
The auction is coming up soon! Save the date and come join in. It’s always a great time.
https://charityauction.bid/HollywoodMuuvieNight"
Date is in past

Auction website references Email: CVUUFAuction@gmail.com
how many of these do we have? Should they be converted to chaliceuu.org or should try to get ChaliceAuction@gmail.com ?

**Comment by GrumpyOldTroll** [comment]
This was edited 2 months ago by Jill to point to 2020's Feb 29th auction.

Found out CVUUFAuction@gmail forwards to Rich Trombino, and was set up to avoid people sending questions to the whole auction committee.  The current page uses only auction@chaliceuu.org, I think we should consider CVUUFAuction@gmail retired, or if one is needed should set up a @chaliceuu.org mail address for it.

The blog post format at the bottom was meant for afterward write-ups of old auctions to remain up, showing how fun they were, but it looks like there's currently only one for last year, and it's worded like a future-looking thing.

I just sent a question to see if we have any such articles with pictures and such for any of the old ones, which I'll post if they're there, else I think I'll delete it.

Leaving this open pending a response.

**Comment by GrumpyOldTroll** [comment]
Rich wrote back.  Didn't really give new website copy, but did send a pdf:
[Chalice Heroes - Taking a Leap of Faith.pdf](https://github.com/CVUUFellowship/church/files/4131647/Chalice.Heroes.-.Taking.a.Leap.of.Faith.pdf)

And a new auctria link:
https://charityauction.bid/HEROES_Taking_a_Leap_of_Faith

I updated the page to embed the pdf and added some links into the auction management page.

It's not great, and could still use more of a real copy-editing pass, but I'll close this because it's no longer grossly inadequate, merely kinda lame.
